name: Node.js CI Demo

on:
    push:
        branches:
            - main


jobs:
    build:
        runs-on: ubuntu-latest    

        steps:
            #step 1: checkout code
            - name: Checkout repository
              uses: actions/checkout@4

            #step 2: setup node.js
            - name: Setup Node.js
              uses: actions/setup-node@4
              with:
                node-version: 18

             #step 3: Install dependencies   
            - name: Install dependencies
              run: npm install
            
            #step 4: Run tests
            - name: Run tests
              run: npm test
